### ISSUE TITLE
Instagram link in profile.

### ISSUE THREAD

**Issue by yuvrock** [fossasia/open-event-attendee-android#2526] opened 2019-12-23 14:59 UTC
There is some issue with the addition of Instagram link in profile. Once the data is entered and the profile is updated and the profile is opened to be edited again, the Instagram link can't be seen like the rest of the name and phone number once the edit pro
![20191222_170323](https://user-images.githubusercontent.com/35378149/71364668-e8552a00-25c2-11ea-82e4-c616633f239c.gif)
file option is clicked on.

**Comment by iamareebjamal** [comment] 2019-12-23 15:22
Duplicate of #2524

**Closed by iamareebjamal** 2019-12-23 15:22 UTC
