### ISSUE TITLE
Password reseting issue

### ISSUE THREAD

**Issue by manyadua16** [fossasia/open-event-attendee-android#2539] opened 2019-12-31 16:01 UTC
Inputs during password reset are vague, and those should be clarified. Also, there is no need to have a create event button during password reset as it is irrelevant.

**Comment by muneebGH** [comment] 2019-12-31 17:13
![ezgif com-optimize](https://user-images.githubusercontent.com/49611774/71628602-8b88ed80-2c1a-11ea-80fb-04859bbb3b57.gif)
 I dont see anything like this

**Comment by iamareebjamal** [comment] 2019-12-31 17:44
Why are you duplicating issues? You have literally copied word by word and created this issue AFTER commenting on the already existing one

Duplicate of #2530

**Closed by iamareebjamal** 2019-12-31 17:44 UTC
