### ISSUE TITLE
Not able to remove liked events.

### ISSUE THREAD

**Issue by VaibhavDM** [fossasia/open-event-attendee-android#2553] opened 2020-01-06 15:42 UTC
**Describe the bug**
When you try to remove liked event it first shows that the event is deleted but the event is not deleted. 

**To Reproduce**

1. Go to likes menu
2. Click on the heart icon to remove an event from liked events
3. It first shows that event is deleted.
4. Then an error will occur

**Expected behavior**

When we click on heart icon the event must be remove from liked events.

**Screenshots**

![WhatsApp Image 2020-01-06 at 20 58 59 (2)](https://user-images.githubusercontent.com/53111996/71828771-0d6c9100-30c9-11ea-872c-db983f15097a.jpeg)
![WhatsApp Image 2020-01-06 at 20 58 59 (1)](https://user-images.githubusercontent.com/53111996/71828781-12c9db80-30c9-11ea-8949-a1466db9fdb9.jpeg)
![WhatsApp Image 2020-01-06 at 20 58 59](https://user-images.githubusercontent.com/53111996/71828787-16f5f900-30c9-11ea-9539-649a9d3a667e.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Vivo Z1pro |
|Android Version| Pie 9 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by Xsniper0** [comment] 2020-01-06 15:50
> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Logs**
> 
> **Screenshots**
> 
> ![WhatsApp Image 2020-01-06 at 20 58 59 (2)](https://user-images.githubusercontent.com/53111996/71828771-0d6c9100-30c9-11ea-872c-db983f15097a.jpeg)
> ![WhatsApp Image 2020-01-06 at 20 58 59 (1)](https://user-images.githubusercontent.com/53111996/71828781-12c9db80-30c9-11ea-8949-a1466db9fdb9.jpeg)
> ![WhatsApp Image 2020-01-06 at 20 58 59](https://user-images.githubusercontent.com/53111996/71828787-16f5f900-30c9-11ea-9539-649a9d3a667e.jpeg)
> 
> **Smartphone Info:**
> 
> Device	
> Android Version	
> **Additional context**
> 
> **Would you like to work on the issue?**
> 
> * [ ]  Yes
> * [ ]  No
> * Other:

**Comment by liveHarshit** [comment] 2020-01-08 05:27
Attach GIF instead.

**Comment by rob729** [comment] 2020-01-13 12:54
@liveHarshit Can I work on this issue?

**Comment by VaibhavDM** [comment] 2020-01-14 13:02
yes you can!!😊

**Comment by rob729** [comment] 2020-01-14 14:24
<a href="https://imgflip.com/gif/3m2zp9"><img src="https://i.imgflip.com/3m2zp9.gif" title="made at imgflip.com"/></a>

**Comment by rob729** [comment] 2020-01-20 14:45
@liveHarshit @iamareebjamal This seems to be a server-side problem. Should I open an issue on the server-side?

**Comment by liveHarshit** [comment] 2020-01-20 16:05
> @liveHarshit @iamareebjamal This seems to be a server-side problem. Should I open an issue on the server-side?

Can't say. Provide server response.

**Comment by rob729** [comment] 2020-01-20 18:08
```
{"errors": [{"status": 409, "source": {"pointer": "/data/relationships/event"}, "title": "Conflict", "detail": "Event already favourited"}], "jsonapi": {"version": "1.0"}}
```

**Comment by rob729** [comment] 2020-01-21 17:36
> @liveHarshit @iamareebjamal This seems to be a server-side problem. Should I open an issue on the server-side?

?? @liveHarshit @iamareebjamal

**Comment by iamareebjamal** [comment] 2020-01-21 19:37
Yes

**Comment by codedsun** [comment] 2020-01-21 20:01
@rob729 - Please open an issue on the server. Thankyou

**Comment by codedsun** [comment] 2020-01-22 14:50
@rob729 - The server side issue is fixed, please check the app side.

**Comment by rob729** [comment] 2020-01-22 15:27
Ok

**Comment by rob729** [comment] 2020-01-22 15:40
@codedsun The issue is still present in the app.

**Comment by iamareebjamal** [comment] 2020-01-22 15:56
You should be using the dev server

**Comment by codedsun** [comment] 2020-01-22 16:03
@rob729 - The release has not been made yet, so please test in on dev server currently. The fix will go to prod once we make a release. Thankyou!

**Comment by rob729** [comment] 2020-01-22 16:13
I am using the debug version of the app.
Does https://open-event-api-dev.herokuapp.com/v1/ indicates dev server?

<blockquote><div><strong><a href="https://open-event-api-dev.herokuapp.com/v1/">404 Not Found</a></strong></div></blockquote>

**Comment by codedsun** [comment] 2020-01-22 16:17
https://open-event-api-dev.herokuapp.com

<blockquote><div><strong><a href="https://open-event-api-dev.herokuapp.com/">Open Event API Server</a></strong></div></blockquote>

**Comment by rob729** [comment] 2020-01-22 16:19
I am still getting the error.
404 NOT FOUND https://open-event-api-dev.herokuapp.com/v1/user-favourite-events/63
```
{"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}
```


<blockquote></blockquote>

**Comment by codedsun** [comment] 2020-01-22 16:52
@rob729 - Their is some bug on the app side. When I try to favourite an event - it hits the api 

 `POST https://open-event-api-dev.herokuapp.com/v1/user-favourite-events` which is fine

then  i want to remove this favourite event - only from the UI the favourite icon is removed from that event and transferred to the next event in the list .

Following, when I try to remove that favourite event. the app hits
`DELETE https://open-event-api-dev.herokuapp.com/v1/user-favourite-events/126` (which was the event I didn't favourited, but the app side shows)

It gives the error
`{"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}`

**Comment by codedsun** [comment] 2020-01-22 16:54
The API end points are working fine and you can hit from postman and check.
The documentation is present here https://open-event-api-dev.herokuapp.com

<blockquote><div><strong><a href="https://open-event-api-dev.herokuapp.com/">Open Event API Server</a></strong></div></blockquote>

**Comment by codedsun** [comment] 2020-01-22 16:59
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20026440/72915662-ab698800-3d66-11ea-9047-bf85371d8164.gif)

Reference

**Comment by codedsun** [comment] 2020-01-22 17:25
So, basically in the list, the event I favourited is first but it shows the second. Please look into this.

**Comment by rob729** [comment] 2020-01-22 17:26
Ok

**Comment by rob729** [comment] 2020-01-22 18:37
In my case, I am getting an error when I am trying to like an event.
409 CONFLICT https://open-event-api-dev.herokuapp.com/v1/user-favourite-events
<a href="https://imgflip.com/gif/3mvs9y"><img src="https://i.imgflip.com/3mvs9y.gif" title="made at imgflip.com"/></a>

**Comment by codedsun** [comment] 2020-01-22 19:32
It's because you have liked that event previously and the UI of app doesn't shows that. I already mentioned that their's is the misplacement of favourite events.

> So, basically in the list, the event I favourited is first but it shows the second. Please look into thiss

**Comment by rob729** [comment] 2020-01-24 07:36
<a href="https://imgflip.com/gif/3n1u8p"><img src="https://i.imgflip.com/3n1u8p.gif" title="made at imgflip.com"/></a>
@codedsun I did a fresh install of the app and now I am not getting the error when I am liking the event but while removing the liked event I am getting the following error.

404 NOT FOUND https://open-event-api-dev.herokuapp.com/v1/user-favourite-events/16
```
{"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}
``` 
Do you have any idea what could be the possible reason for this error?

<blockquote></blockquote>

**Comment by codedsun** [comment] 2020-01-24 07:39
@rob729  - I told you that there is a misplacement of the favourite button in UI. Please use POSTMAN and test from their.

**Comment by rob729** [comment] 2020-01-24 18:00
<a href="https://imgflip.com/gif/3n2pqk"><img src="https://i.imgflip.com/3n2pqk.gif" title="made at imgflip.com"/></a>

@liveHarshit @iamareebjamal I created a new account on the app and then tested it. The app is working fine  for the events liked after https://github.com/fossasia/open-event-server/issues/6762 was fixed. 
Can you please suggest me how to proceed on this issue further as I am not able to figure out what to do about liked events that are showing error when like is removed?

**Comment by ankushmundhra** [comment] 2020-01-26 06:41
@Xsniper0 Is this issue still on? I think i may have an idea to solve this issue!

**Comment by VaibhavDM** [comment] 2020-01-26 13:16
Yes this issue is still on

**Comment by ankushmundhra** [comment] 2020-01-27 03:45
@Xsniper0 Can i work on this?

**Comment by rob729** [comment] 2020-01-27 05:32
Yes

**Comment by VaibhavDM** [comment] 2020-01-27 19:56
Yes!!

**Closed as completed** 2023-04-29 12:48 UTC
