### ISSUE TITLE
App crashes on clicking "View" when having Donation Tickets

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2241] opened 2019-08-05 04:57 UTC
**Describe the bug**
App crashes on clicking "View" when having Donation Tickets

**Screenshots**
<img src="https://i.ibb.co/vzjVwQT/ezgif-1-e07e1b780106.gif" alt="ezgif-1-e07e1b780106" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment] 2019-08-05 05:02
Duplicate of #2234

**Closed by liveHarshit** 2019-08-05 05:02 UTC

**Comment by liveHarshit** [comment] 2019-08-05 05:05
@anhanh11001 Sorry I have not mentioned how to reproduce in #2234
