### ISSUE TITLE
Bug in updating Facebook link in profile.

### ISSUE THREAD

**Issue by yuvrock** [fossasia/open-event-attendee-android#2525] opened 2019-12-23 14:56 UTC
There is some issue with the addition of Facebook link in profile.
![20191222_165507](https://user-images.githubusercontent.com/35378149/71364496-6bc24b80-25c2-11ea-8ab6-a275c79c1594.gif)

**Comment by iamareebjamal** [comment] 2019-12-23 15:22
Duplicate of #2524

**Closed by iamareebjamal** 2019-12-23 15:22 UTC
